#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_DIR/.tunnel.env"

echo "================================="
echo "  Terminal Mobile — ngrok Setup"
echo "================================="
echo ""

# 1. Check prerequisites
echo "Checking prerequisites..."

if ! command -v node &> /dev/null; then
  echo "ERROR: Node.js is not installed. Please install Node.js >= 18."
  exit 1
fi

NODE_VERSION=$(node -v | sed 's/v//' | cut -d. -f1)
if [ "$NODE_VERSION" -lt 18 ]; then
  echo "ERROR: Node.js >= 18 is required. Found: $(node -v)"
  exit 1
fi
echo "  Node.js $(node -v) — OK"

# 2. Install ngrok
if ! command -v ngrok &> /dev/null; then
  echo ""
  echo "ngrok is not installed."

  OS=$(uname -s)
  ARCH=$(uname -m)

  case "$OS" in
    Darwin)
      if command -v brew &> /dev/null; then
        echo "Installing via Homebrew..."
        brew install ngrok/ngrok/ngrok
      else
        echo "Please install Homebrew first, then run: brew install ngrok/ngrok/ngrok"
        echo "Or download from: https://ngrok.com/download"
        exit 1
      fi
      ;;
    Linux)
      echo "Downloading ngrok binary..."
      case "$ARCH" in
        x86_64) ARCH_NAME="amd64" ;;
        aarch64|arm64) ARCH_NAME="arm64" ;;
        *) echo "Unsupported architecture: $ARCH"; exit 1 ;;
      esac
      curl -fsSL -o /tmp/ngrok.tgz "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-${ARCH_NAME}.tgz"
      tar -xzf /tmp/ngrok.tgz -C /tmp
      chmod +x /tmp/ngrok
      sudo mv /tmp/ngrok /usr/local/bin/ngrok
      rm -f /tmp/ngrok.tgz
      ;;
    *)
      echo "Unsupported OS: $OS"
      echo "Download ngrok from: https://ngrok.com/download"
      exit 1
      ;;
  esac
fi

echo "  ngrok $(ngrok version 2>&1) — OK"

# 3. Configure authtoken
echo ""
echo "Step 1: Add your ngrok authtoken"
echo ""
echo "  1. Sign up or log in at: https://dashboard.ngrok.com"
echo "  2. Copy your authtoken from: https://dashboard.ngrok.com/get-started/your-authtoken"
echo ""
read -p "Paste your authtoken: " AUTHTOKEN

if [ -z "$AUTHTOKEN" ]; then
  echo "ERROR: Authtoken is required."
  exit 1
fi

ngrok config add-authtoken "$AUTHTOKEN"
echo "  Authtoken saved."

# 4. Get static domain
echo ""
echo "Step 2: Enter your free static domain"
echo ""
echo "  1. Go to: https://dashboard.ngrok.com/domains"
echo "  2. Claim your free static domain (one per account)"
echo "  3. Copy the domain (e.g., something.ngrok-free.app)"
echo ""

# Show existing domain as default if .tunnel.env exists
EXISTING_DOMAIN=""
if [ -f "$ENV_FILE" ]; then
  EXISTING_DOMAIN=$(grep '^NGROK_DOMAIN=' "$ENV_FILE" 2>/dev/null | cut -d= -f2)
fi

if [ -n "$EXISTING_DOMAIN" ]; then
  read -p "Enter your static domain [$EXISTING_DOMAIN]: " DOMAIN
  DOMAIN="${DOMAIN:-$EXISTING_DOMAIN}"
else
  read -p "Enter your static domain: " DOMAIN
fi

if [ -z "$DOMAIN" ]; then
  echo "ERROR: Domain is required."
  exit 1
fi

# Validate domain format
if ! echo "$DOMAIN" | grep -qE '^[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?)+$'; then
  echo "ERROR: Invalid domain format: $DOMAIN"
  exit 1
fi

# 5. Save config
cat > "$ENV_FILE" << EOF
# ngrok tunnel configuration
# Generated by setup-ngrok.sh — do not commit this file
NGROK_DOMAIN=$DOMAIN
EOF

echo ""
echo "  Domain saved to .tunnel.env"

# 6. Done
echo ""
echo "================================="
echo "  Setup complete!"
echo ""
echo "  Start the app + tunnel:"
echo "    npm run tunnel"
echo ""
echo "  Your app will be at:"
echo "    https://$DOMAIN"
echo "================================="
